module.exports.User = require("./user.model")
module.exports.owner = require("./owner.model")
module.exports.shop = require("./restaurant.model")
module.exports.Delivery = require("./Delivery.model")
module.exports.Order = require("./Order.model")
module.exports.coadmin = require("./coadmin.model")
module.exports.Food = require("./food.model")
module.exports.login = require("./login.model")